# examples/0002-small-network-paras.toml
[relaychain]
default_image = "docker.io/parity/polkadot:latest"
default_command = "polkadot"
chain = "kusama-local"

  [[relaychain.node_groups]]
  name = "validator"
  count = 5

[[parachains]]
id = 1000
cumulus_based = true
chain = "statemine-local"

  [parachains.collator]
  name = "collator01"
  image = "docker.io/parity/polkadot-parachain:latest"
  command = "polkadot-parachain"

[[parachains]]
id = 1001
cumulus_based = true

  [parachains.collator]
  name = "collator01"
  image = "docker.io/parity/polkadot-parachain:latest"
  command = "polkadot-parachain"
