# examples/0002-small-network-paras.toml
[relaychain]
default_image = "docker.io/parity/polkadot:latest"
default_command = "polkadot"
chain = "kusama-local"

  [[relaychain.node_groups]]
  name = "validator"
  count = 2

[[parachains]]
id = 1001
cumulus_based = true
#chain = "subzero-local"
chain = "statemint-local"

  [parachains.collator]
  name = "collator02"
  image = "docker.io/parity/polkadot-parachain:latest"
  command = "polkadot-parachain-sub0"
  args = ["-lparachain=debug", "-laura=debug"]
